services:
  - type: web
    name: football-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: db_uri
        value: staging
    plan: free
